
title: Andy Marthin Christo | Resume
url: 'https://andy.marthin.web.id'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
#style: styles-4
#style: styles-5
# style: styles-6


#Profile information
name: Andy Marthin Christo
tagline: Software Engineer
pic: photo.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: andy@marthin.web.id
phone: +62 8539 5777 873
website: blog.marthin.web.id #do not add http://
linkedin: andymarthin
github: andymarthin
twitter: '@andymarthin'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
plugins:

skills:
  - 
    name: "Ruby on Rails"
    level: 80
  -
    name: "Git"
    level: 80
  -
    name: JavaScript
    level: 70
  
  - 
    name: PHP
    level: 60
  
  -
    name: Trello
    level: 70
  
  -
    name: MySql
    level: 70
  
  -
    name: PostgreSQL
    level: 70
  
  - 
    name: Laravel
    level: 60


educations:
  -
    major: "Teknik Informatika"
    school: "STMIK Bina Mulia"
    year: "2010-2014"

languages:
  -
    name: "Indonesia"
    level: "Native"
  -
    name: "English"
    level: "Profesional"

Interests:
  - 
    name: "Programming"
  - 
    name: "Linux"

experiences:
  - 
    company: "PT Veit Solusi Indonesia"
    position: "Junior Programmer"
    location: "Jakarta"
    from: Juny 2017
    until: September 2017
    description: ""
    jobs:
      - desc: Develop Web Service Using Laravel
      - desc: Develop iOS App using XCode and Swift 3
      - desc: Android App using Android Studio and java

projects:
  -
    name: Database Karyawan Universitas Bung Karno
    description: The desktop-based employee information system of the University of Bung Karno was built using JAVA and H2 as a database.
    url: "#"

  -
    name: Nakito Studio 
    description: A responsive website template designed to help web developers/designers market their services. 
    url: "http://nakitostudio.com"

  -
    name: Sistem Informasi Distribusi Abstrak
    description: Sistem Informasi Berbasis Web
    url: "#"

